keys:
  - &fpletz D9C081E4C7F11E7F04CC7EAFBE2418F5C8A0CD6C
  - &globin 0B0D37F530B74C80FB88276C14E3BEE96E5C5807

key_groups:
  - &cd
    pgp:
      - *fpletz
      - *globin
    age:
      # argocd sops key
      - age1zd93w99zc846w379wftnxyquelfh4g45t2uejcn579n2hm257s3qy9u8sn

creation_rules:
  - path_regex: ".+\\.sops\\.ya?ml$"
    key_groups:
      - *cd
