name: update-flake-lock
on:
  workflow_dispatch:
  schedule:
    - cron: '20 4 * * *'

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v20
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          pr-title: "Update flake.lock"
          pr-assignees: fpletz
          pr-labels: |
            dependencies
            automated
